### ISSUE TITLE
Assertion of throw()

### ISSUE THREAD

**Issue by treylav** [bfrymire/crispy#27]
Hello.

Do you think functionality like [pytest.rises](https://docs.pytest.org/en/latest/reference/reference.html#pytest-raises) would be useful for **crispy**?
The idea is that the test case expects a raise of exception and if the specified exception was raised, the assertion returns True. In the case of GML, this could be `throw()` with certain parameters.

Already now I can implement such functionality with **crispy**, but it turns out to be quite verbose:

```haxe
function never_enough(number) {
	enum errors
	{
		toobig,
		toosmall,
	}

	if number > 42
		{
		throw(errors.toobig)
		}
		else
		{
		throw(errors.toosmall)	
		}
}


runner = new TestRunner("runner");
suite = new TestSuite("suite");
runner.addTestSuite(suite);

test_too_small = new TestCase("test_too_small", function() {
	try
	{
		never_enough(34)
	}
	catch(_err)
	{
		assertEqual(_err, errors.toosmall)
	}
});
suite.addTestCase(test_too_small);


test_too_big = new TestCase("test_too_big", function() {
	try
	{
		never_enough(43)
	}
	catch(_err)
	{
		assertEqual(_err, errors.toobig)
	}
});
suite.addTestCase(test_too_big);

runner.run();
```

Thanks for your attention and your project.

**Comment by bfrymire** [comment]
Hello 👋 

Thank you for submitting your feature request and your interest in the library!

Passing the enums through `throw()` works in the example, but would lead to having to write error messages in a specific way that would not be readily apparent to the end user. Outside of testing, having the method throw `0` or `1` wouldn't convey what the error was.

I think this would be a nice feature to add. I'm not exactly sure what the best way would be to implement it at the moment. A couple of my goals would be to keep the user from having to write out a verbose enum or the try/catch statement. I'll have to look into it further.

**Comment by bfrymire** [comment]
@treylav my apologies for not getting to this sooner. Thank you for the feature suggestion.

Added `assertRaises` and `assertRaiseErrorValue`.
